#!/usr/bin/env bash
chmod 777 launch.sh
cd tg
wget "https://valtman.name/files/telegram-cli-1222"
mv telegram-cli-1222 tg
cd ..
sudo pip3 install redis
sudo service redis-server restart
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade
sudo ppa-purge
sudo apt-get install libreadline-dev libconfig-dev libssl-dev lua5.2 liblua5.2-dev lua-socket lua-sec lua-expat libevent-dev make unzip git redis-server autoconf g++ libjansson-dev libpython-dev expat libexpat1-dev ppa-purge python3-pip python3-dev
RED='\033[0;31m'
NC='\033[0m'
CYAN='\033[0;36m'
echo -e "${CYAN}Install Completed! input ./launch.sh for launch bot ${NC}"
echo "\033[38;5;110m
██╗  ██╗████████╗██████╗ ██╗ █████╗
╚██╗██╔╝╚══██╔══╝██╔══██╗██║██╔══██╗
 ╚███╔╝    ██║   ██████╔╝██║███████║
 ██╔██╗    ██║   ██╔══██╗██║██╔══██║
██╔╝ ██╗   ██║   ██║  ██║██║██║  ██║
╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═╝╚═╝╚═╝  ╚═╝
\033[0m\n"
exit
# @mafia_cli
#https://github.com/mafia-007



